// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class HelloWorld;
@class HelloWorld_Builder;

@interface HelloWorldReqRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface HelloWorld : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasOpt_:1;
  BOOL hasStr_:1;
  int32_t id;
  int32_t opt;
  NSString* str;
}
- (BOOL) hasId;
- (BOOL) hasStr;
- (BOOL) hasOpt;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* str;
@property (readonly) int32_t opt;

+ (HelloWorld*) defaultInstance;
- (HelloWorld*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HelloWorld_Builder*) builder;
+ (HelloWorld_Builder*) builder;
+ (HelloWorld_Builder*) builderWithPrototype:(HelloWorld*) prototype;

+ (HelloWorld*) parseFromData:(NSData*) data;
+ (HelloWorld*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HelloWorld*) parseFromInputStream:(NSInputStream*) input;
+ (HelloWorld*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HelloWorld*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HelloWorld*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HelloWorld_Builder : PBGeneratedMessageBuilder {
@private
  HelloWorld* result;
}

- (HelloWorld*) defaultInstance;

- (HelloWorld_Builder*) clear;
- (HelloWorld_Builder*) clone;

- (HelloWorld*) build;
- (HelloWorld*) buildPartial;

- (HelloWorld_Builder*) mergeFrom:(HelloWorld*) other;
- (HelloWorld_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HelloWorld_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (HelloWorld_Builder*) setId:(int32_t) value;
- (HelloWorld_Builder*) clearId;

- (BOOL) hasStr;
- (NSString*) str;
- (HelloWorld_Builder*) setStr:(NSString*) value;
- (HelloWorld_Builder*) clearStr;

- (BOOL) hasOpt;
- (int32_t) opt;
- (HelloWorld_Builder*) setOpt:(int32_t) value;
- (HelloWorld_Builder*) clearOpt;
@end

