// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class UserAction;
@class UserAction_Builder;

@interface UserActionRequestRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface UserAction : PBGeneratedMessage {
@private
  BOOL hasUid_:1;
  BOOL hasVersion_:1;
  BOOL hasUserAction_:1;
  BOOL hasChannel_:1;
  BOOL hasDeviceType_:1;
  BOOL hasDeviceId_:1;
  BOOL hasSysVersion_:1;
  BOOL hasLanguage_:1;
  BOOL hasTimeZone_:1;
  BOOL hasResolution_:1;
  int32_t uid;
  NSString* version;
  NSString* userAction;
  NSString* channel;
  NSString* deviceType;
  NSString* deviceId;
  NSString* sysVersion;
  NSString* language;
  NSString* timeZone;
  NSString* resolution;
}
- (BOOL) hasUid;
- (BOOL) hasVersion;
- (BOOL) hasUserAction;
- (BOOL) hasChannel;
- (BOOL) hasDeviceType;
- (BOOL) hasDeviceId;
- (BOOL) hasSysVersion;
- (BOOL) hasLanguage;
- (BOOL) hasTimeZone;
- (BOOL) hasResolution;
@property (readonly) int32_t uid;
@property (readonly, retain) NSString* version;
@property (readonly, retain) NSString* userAction;
@property (readonly, retain) NSString* channel;
@property (readonly, retain) NSString* deviceType;
@property (readonly, retain) NSString* deviceId;
@property (readonly, retain) NSString* sysVersion;
@property (readonly, retain) NSString* language;
@property (readonly, retain) NSString* timeZone;
@property (readonly, retain) NSString* resolution;

+ (UserAction*) defaultInstance;
- (UserAction*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserAction_Builder*) builder;
+ (UserAction_Builder*) builder;
+ (UserAction_Builder*) builderWithPrototype:(UserAction*) prototype;

+ (UserAction*) parseFromData:(NSData*) data;
+ (UserAction*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserAction*) parseFromInputStream:(NSInputStream*) input;
+ (UserAction*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserAction*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserAction*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserAction_Builder : PBGeneratedMessageBuilder {
@private
  UserAction* result;
}

- (UserAction*) defaultInstance;

- (UserAction_Builder*) clear;
- (UserAction_Builder*) clone;

- (UserAction*) build;
- (UserAction*) buildPartial;

- (UserAction_Builder*) mergeFrom:(UserAction*) other;
- (UserAction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserAction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (int32_t) uid;
- (UserAction_Builder*) setUid:(int32_t) value;
- (UserAction_Builder*) clearUid;

- (BOOL) hasVersion;
- (NSString*) version;
- (UserAction_Builder*) setVersion:(NSString*) value;
- (UserAction_Builder*) clearVersion;

- (BOOL) hasUserAction;
- (NSString*) userAction;
- (UserAction_Builder*) setUserAction:(NSString*) value;
- (UserAction_Builder*) clearUserAction;

- (BOOL) hasChannel;
- (NSString*) channel;
- (UserAction_Builder*) setChannel:(NSString*) value;
- (UserAction_Builder*) clearChannel;

- (BOOL) hasDeviceType;
- (NSString*) deviceType;
- (UserAction_Builder*) setDeviceType:(NSString*) value;
- (UserAction_Builder*) clearDeviceType;

- (BOOL) hasDeviceId;
- (NSString*) deviceId;
- (UserAction_Builder*) setDeviceId:(NSString*) value;
- (UserAction_Builder*) clearDeviceId;

- (BOOL) hasSysVersion;
- (NSString*) sysVersion;
- (UserAction_Builder*) setSysVersion:(NSString*) value;
- (UserAction_Builder*) clearSysVersion;

- (BOOL) hasLanguage;
- (NSString*) language;
- (UserAction_Builder*) setLanguage:(NSString*) value;
- (UserAction_Builder*) clearLanguage;

- (BOOL) hasTimeZone;
- (NSString*) timeZone;
- (UserAction_Builder*) setTimeZone:(NSString*) value;
- (UserAction_Builder*) clearTimeZone;

- (BOOL) hasResolution;
- (NSString*) resolution;
- (UserAction_Builder*) setResolution:(NSString*) value;
- (UserAction_Builder*) clearResolution;
@end

