......
xcodeproj './BuShangBanApp/BuShangBanApp.xcodeproj'
......
platform :ios, '7.0'

pod 'FMDB'
pod 'AFNetworking'
pod 'MJExtension'
pod 'MBProgressHUD'
pod 'MBProgressHUD+BWMExtension'
pod 'SDWebImage'
pod 'UICKeyChainStore'


#pod 'UMengAnalytics'            #标准SDK，含IDFA
#pod 'UMengAnalytics-NO-IDFA'    #无IDFA版SDK（请根据需要选择其中一个）

pod 'YTKKeyValueStore'
pod 'YTKNetwork'
pod 'YTKNetworkExtension'

pod 'ProtocolBuffers'

pod 'Masonry'
pod 'pop'
pod 'POP+MCAnimate'
pod 'NJKWebViewProgress'
pod 'EGOTableViewPullRefresh'
pod 'iCarousel'
pod 'JDStatusBarNotification'
pod 'KVOController'
pod 'YYKit'
#pod 'YYModel'
#pod 'YYCache'
#pod 'YYImage'
#pod 'YYWebImage'
#pod 'YYText'
#pod 'YYKeyboardManager'
#pod 'YYDispatchQueuePool'
#pod 'YYAsyncLayer'
#pod 'YYCategories'

#pod 'NetworkEye'
pod 'RegExCategories'
pod 'AsyncDisplayKit'

pod 'JSPatch'

